// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa-R-eXo9PQSvh1jgM4LgqGOsk61gXM1Y',
    appId: '1:86718160418:web:eaae7c702ea86fd0c0b47b',
    messagingSenderId: '86718160418',
    projectId: 'my-mini-closets',
    authDomain: 'my-mini-closets.firebaseapp.com',
    storageBucket: 'my-mini-closets.appspot.com',
    measurementId: 'G-KCP6DZ8XJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnsgX8xAcPMANOu3FXTjSndvgunB4tLg4',
    appId: '1:86718160418:android:32882b01ab1f2aecc0b47b',
    messagingSenderId: '86718160418',
    projectId: 'my-mini-closets',
    storageBucket: 'my-mini-closets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA6fn9Uh96WXLkUd3BqvojrWHG0broZpE',
    appId: '1:86718160418:ios:048e0a32c1773dddc0b47b',
    messagingSenderId: '86718160418',
    projectId: 'my-mini-closets',
    storageBucket: 'my-mini-closets.appspot.com',
    iosBundleId: 'com.example.myminicloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA6fn9Uh96WXLkUd3BqvojrWHG0broZpE',
    appId: '1:86718160418:ios:048e0a32c1773dddc0b47b',
    messagingSenderId: '86718160418',
    projectId: 'my-mini-closets',
    storageBucket: 'my-mini-closets.appspot.com',
    iosBundleId: 'com.example.myminicloset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa-R-eXo9PQSvh1jgM4LgqGOsk61gXM1Y',
    appId: '1:86718160418:web:3573bb831202e740c0b47b',
    messagingSenderId: '86718160418',
    projectId: 'my-mini-closets',
    authDomain: 'my-mini-closets.firebaseapp.com',
    storageBucket: 'my-mini-closets.appspot.com',
    measurementId: 'G-FRT52KKBLD',
  );

}